INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO projects(title, category, funding_goal, start_date,end_date) VALUES('a','a',10,'10/1/19','12/31/19');
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO users(name, age) VALUES('a',10);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,10,1);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,17,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,8,10);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,11,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,1,7);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,2,8);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,5,9);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,7,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,1,3);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,8,3);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,10,1);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,17,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,8,10);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,11,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,1,7);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,2,8);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,5,9);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,7,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,1,3);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,8,3);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,10,1);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,17,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,8,10);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,11,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,1,7);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,2,8);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,5,9);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,7,2);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,1,3);
INSERT INTO pledgES(amount, user_id, project_id) VALUES(100,8,3);